import { useEffect, useState } from "react";

const buildUrl = (path) => {
  const base = import.meta.env.BASE_URL ?? "/";
  const normalized = path.startsWith("/") ? path.slice(1) : path;
  return `${base}${normalized}`;
};

function useSeries(path) {
  const [state, setState] = useState({ status: "idle", rows: [] });

  useEffect(() => {
    let cancelled = false;

    async function load() {
      setState({ status: "loading", rows: [] });
      try {
        const response = await fetch(buildUrl(path), { cache: "no-store" });
        if (!response.ok) {
          throw new Error(`Request failed with status ${response.status}`);
        }
        const payload = await response.json();
        const rows = Array.isArray(payload?.observations)
          ? payload.observations.map((entry) => ({
              date: entry.date,
              value: Number.parseFloat(entry.value),
            }))
          : [];
        if (!cancelled) {
          setState({ status: "loaded", rows });
        }
      } catch (error) {
        if (!cancelled) {
          setState({ status: "error", rows: [] });
        }
      }
    }

    load();

    return () => {
      cancelled = true;
    };
  }, [path]);

  return state;
}

function formatNumber(value) {
  if (Number.isNaN(value)) {
    return "—";
  }
  return new Intl.NumberFormat("en-US", {
    maximumFractionDigits: 2,
  }).format(value);
}

function SeriesCard({ title, path }) {
  const { status, rows } = useSeries(path);

  const latest = rows.at(-1);
  const previous = rows.at(-2);

  let body;

  if (status === "loading") {
    body = <p className="data-card__status">Loading…</p>;
  } else if (status === "error") {
    body = (
      <p className="data-card__status data-card__status--error">
        Data not available. Run the fetch workflow to populate this feed.
      </p>
    );
  } else if (!latest) {
    body = (
      <p className="data-card__status">
        No observations yet. The GitHub Actions job writes the daily snapshot
        here once it completes.
      </p>
    );
  } else {
    body = (
      <div className="data-card__body">
        <div>
          <span className="data-card__label">Latest</span>
          <strong>{formatNumber(latest.value)}</strong>
          <span className="data-card__date">{latest.date}</span>
        </div>
        {previous ? (
          <div>
            <span className="data-card__label">Prev.</span>
            <strong>{formatNumber(previous.value)}</strong>
            <span className="data-card__date">{previous.date}</span>
          </div>
        ) : null}
        <div>
          <span className="data-card__label">Observations</span>
          <strong>{rows.length}</strong>
        </div>
      </div>
    );
  }

  return (
    <article className="data-card">
      <h3>{title}</h3>
      {body}
    </article>
  );
}

export default function DataSnapshots({ sectionRef = null }) {
  return (
    <section
      className="site-wrap data-snapshots"
      ref={sectionRef}
      id="data"
    >
      <h2>Daily snapshot</h2>
      <p className="data-snapshots__intro">
        These feeds are generated by the GitHub Actions fetch job. Once the job
        runs with your FRED API key, the latest measurements will appear here.
      </p>
      <div className="data-snapshots__grid">
        <SeriesCard title="S&amp;P 500 index (price)" path="data/sp500.json" />
        <SeriesCard
          title="S&amp;P 500 index (total return)"
          path="data/sp500_total_return.json"
        />
      </div>
    </section>
  );
}
